// Generated by CoffeeScript 1.3.1
(function() {
  var app, chat, express, io, preprocessor, sealdeal, socketio;

  express = require('express');

  socketio = require('socket.io');

  sealdeal = require('../sealdeal');

  app = express.createServer();

  app.configure(function() {
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    return app.use(app.router);
  });

  app.configure(function() {
    return app.use(express["static"](__dirname + '/public'));
  });

  app.configure('development', function() {
    return app.use(express.errorHandler({
      dumpExceptions: true,
      showStack: true
    }));
  });

  app.configure('production', function() {
    return app.use(express.errorHandler());
  });

  preprocessor = sealdeal.preprocessorRoute(__dirname + '/public', {});

  app.get('/*', preprocessor);

  app.get('/', function(req, res, next) {
    req.params[0] = "/index.html";
    return preprocessor(req, res, next);
  });

  app.listen(process.env.PORT || 5000);

  io = socketio.listen(app);

  chat = io.on('connection', function(socket) {
    return socket.on('message', function(msg) {
      return chat.sockets.send(msg);
    });
  });

}).call(this);
